apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-e00i
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-e00i
    app.kubernetes.io/part-of: test-app-wxzc
  name: devfile-sample-hello-world-e00i
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: devfile-sample-hello-world-e00i
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: devfile-sample-hello-world-e00i
    spec:
      containers:
      - image: hello-world:latest
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
